I3-Project/Delivery_Service

- src/main/java/com/i3/delivery/DeliveryApplication.java
- src/main/java/com/i3/delivery/domain/order/dto/response/OrderResponseDto.java
- src/main/java/com/i3/delivery/domain/order/entity/Order.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/global/config/JpaConfig.java
- **as-is**
- (변경 전 설명을 여기에 작성)
- **to-be**
- (변경 후 설명을 여기에 작성)
> Fix: 버그 수정

- src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreInfoResponseDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationRequestDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationResponseDto.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
1. 필요 없는 column 삭제
2. 생성자 삭제
3. 로그인한 유저 정보 가져와 deleted에 추가
1. 유저 권한 추가 및 연동 작업
1. 정적팩토리메서드로 변경
1. 정적팩토리메서드로 변경
1. 총 리뷰 수 계산 후 업데이트 기능 추가
1. 빌더패턴으로 변경
- **as-is**
- (변경 전 설명을 여기에 작성)
- **to-be**
- (변경 후 설명을 여기에 작성)
> Fix: 버그 수정 및 유저 연동 작업

- src/main/java/com/i3/delivery/domain/category/controller/CategoryController.java
- src/main/java/com/i3/delivery/domain/category/dto/CategoryRequestDto.java
- src/main/java/com/i3/delivery/domain/category/dto/CategoryResponseDto.java
- src/main/java/com/i3/delivery/domain/category/entity/Category.java
- src/main/java/com/i3/delivery/domain/category/repository/CategoryRepository.java
- src/main/java/com/i3/delivery/domain/category/service/CategoryService.java
- src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreEditRequsetDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreEditResponseDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreInfoResponseDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationRequestDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationResponseDto.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
그에 따른 나머지 메소드 카테고리로 변경
- **as-is**
- (변경 전 설명을 여기에 작성)
- **to-be**
- (변경 후 설명을 여기에 작성)
> Fix: 버그 수정 및 Category Entity 추가

- src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
- src/main/java/com/i3/delivery/domain/product/dto/ProductRegistrationRequestDto.java
- src/main/java/com/i3/delivery/domain/product/dto/ProductRegistrationResponseDto.java
- src/main/java/com/i3/delivery/domain/product/entity/Product.java
- src/main/java/com/i3/delivery/domain/product/enums/ProductStatus.java
- src/main/java/com/i3/delivery/domain/product/repository/ProductRepository.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
- src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreEditResponseDto.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
- src/main/java/com/i3/delivery/global/BaseEntity.java
- **to-be**
- Product Domain 생성
- Store 자잘한 버그들 수정
- Store에서 작업해야 할 내용을 깃허브 이슈로 인해 product 브랜치에서 작업하였습니다. 양해부탁드립니다.
> Feature product

- src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
- src/main/java/com/i3/delivery/domain/product/dto/ProductInfoResponseDto.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- **as-is**
- (변경 전 설명을 여기에 작성)
- **to-be**
- Product 단건 조회 API 구현
- Store update set으로 변경
> Feat: Product 정보 조회 기능 구현

- src/main/java/com/i3/delivery/domain/category/controller/CategoryController.java
- src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
- src/main/java/com/i3/delivery/domain/product/dto/ProductEditRequestDto.java
- src/main/java/com/i3/delivery/domain/product/dto/ProductEditResponseDto.java
- src/main/java/com/i3/delivery/domain/product/entity/Product.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
1. Product 수정 API 구현
2. CategoryController 원한 이름 변경
> Feat: Product 수정 조회 기능 구현

- src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
- src/main/java/com/i3/delivery/domain/product/entity/Product.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
1. Product 삭제 API 구현
2. MASTER 일 시 HardDelete 가능
> Feat: Product 삭제 기능 구현

- src/main/java/com/i3/delivery/domain/review/controller/ReviewController.java
- src/main/java/com/i3/delivery/domain/review/dto/ReviewResponseDto.java
- src/main/java/com/i3/delivery/domain/review/entity/Review.java
- src/main/java/com/i3/delivery/domain/review/service/ReviewService.java
Controller 권한 체크 수정, review 등록 및 수정 시 버그 수정
> Fix : Controller 권한 체크 수정 및 기능 버그 수정 (등록, 수정)

- src/main/java/com/i3/delivery/domain/review/controller/ReviewController.java
- src/main/java/com/i3/delivery/domain/review/entity/Review.java
- src/main/java/com/i3/delivery/domain/review/repository/ReviewRepository.java
- src/main/java/com/i3/delivery/domain/review/service/ReviewService.java
> Feature review

- src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
- src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreEditRequsetDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreEditResponseDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreInfoResponseDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationRequestDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationResponseDto.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreReviewResponseDto.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
> Feat: Store, Product 전체조회 API Pageable 적용

- src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
- src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
1. 내용 생략
-  * 현재 WebSecurityConfig에 
.requestMatchers("/api/stores/**").permitAll() 
등을 추가하지 않으면 로직이 동작하지 않는 버그가 있음.
> Feat: Store, Product 리뷰 조회 API Pageable 적용

- src/main/java/com/i3/delivery/domain/user/controller/UserController.java
- src/main/java/com/i3/delivery/domain/user/dto/SignupRequestDto.java
- src/main/java/com/i3/delivery/domain/user/entity/User.java
- src/main/java/com/i3/delivery/domain/user/service/UserService.java
유저 삭제 기능
1. 본인이 삭제하는 기능
2. MANAGER, MASTER 권한 가진 유저가 특정 유저를 삭제하는 기능
유저 도메인 완료했습니다.
> Feature user

- src/main/java/com/i3/delivery/global/exception/category/AlreadyExistCategoryException.java
- src/main/java/com/i3/delivery/global/exception/category/CategoryNotFoundException.java
- src/main/java/com/i3/delivery/global/exception/common/AuthorizationException.java
- src/main/java/com/i3/delivery/global/exception/common/BusinessException.java
- src/main/java/com/i3/delivery/global/exception/common/ErrorCode.java
- src/main/java/com/i3/delivery/global/exception/common/GlobalExceptionHandler.java
- src/main/java/com/i3/delivery/global/exception/common/UnAuthorizedModifyException.java
- src/main/java/com/i3/delivery/global/exception/jwt/ExpiredJwtTokenException.java
- src/main/java/com/i3/delivery/global/exception/jwt/InvalidJwtException.java
- src/main/java/com/i3/delivery/global/exception/jwt/InvalidJwtSignatureException.java
- src/main/java/com/i3/delivery/global/exception/jwt/InvalidRefreshTokenException.java
- src/main/java/com/i3/delivery/global/exception/jwt/JwtInvalidException.java
- src/main/java/com/i3/delivery/global/exception/jwt/NoJwtException.java
- src/main/java/com/i3/delivery/global/exception/jwt/UnsupportedGrantTypeException.java
- src/main/java/com/i3/delivery/global/exception/jwt/UnsupportedJwtTokenException.java
- src/main/java/com/i3/delivery/global/exception/product/ProductNotFoundException.java
- src/main/java/com/i3/delivery/global/exception/response/ApiResponse.java
- src/main/java/com/i3/delivery/global/exception/store/StoreNotFoundException.java
- [v ] 신규 기능 추가/수정
내용 생략
- 다른 에러 처리 핸들러 추가 필요
- ApiResponse로 변경 필요
> Feat: Global 에러 처리 및 ApiResponse 기능 구현

- src/main/java/com/i3/delivery/domain/order/entity/enums/OrderStatusEnum.java
- src/main/java/com/i3/delivery/domain/payment/controller/PaymentController.java
- src/main/java/com/i3/delivery/domain/payment/controller/PaymentCotroller.java
- src/main/java/com/i3/delivery/domain/payment/dto/PaymentRequestDto.java
- src/main/java/com/i3/delivery/domain/payment/dto/PaymentResponseDto.java
- src/main/java/com/i3/delivery/domain/payment/dto/PaymentStatusRequestDto.java
- src/main/java/com/i3/delivery/domain/payment/entity/Payment.java
- src/main/java/com/i3/delivery/domain/payment/entity/enums/PaymentStatusEnum.java
- src/main/java/com/i3/delivery/domain/payment/repository/PaymentRepository.java
- src/main/java/com/i3/delivery/domain/payment/service/PaymentService.java
> Feature payment

- src/main/java/com/i3/delivery/domain/category/service/CategoryService.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Store, Category, Product 에러 처리 API 수정
> Feat: 에러 처리 기능 구현

- src/main/java/com/i3/delivery/domain/cart/entity/Cart.java
> Feat: Cart domain init entity

- src/main/java/com/i3/delivery/domain/category/service/CategoryService.java
- src/main/java/com/i3/delivery/domain/product/entity/Product.java
- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
1. getUserNickName -> getUserName으로 변경
2. 생성 시 UUID 추가
3. productList 추가
1. getUserNickName -> getUserName으로 변경
2. 생성 시 UUID 추가
1. 생성 시 UUID 추가
> Feature store

- src/main/java/com/i3/delivery/domain/cart/entity/Cart.java
- src/main/java/com/i3/delivery/domain/order/controller/OrderController.java
- src/main/java/com/i3/delivery/domain/order/dto/request/OrderRequestDto.java
- src/main/java/com/i3/delivery/domain/order/dto/response/OrderListResponseDto.java
- src/main/java/com/i3/delivery/domain/order/dto/response/OrderResponseDto.java
- src/main/java/com/i3/delivery/domain/order/entity/Order.java
- src/main/java/com/i3/delivery/domain/order/service/OrderService.java
> Feat : 장바구니 기반 주문 생성 기능 구현

- src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreReviewMeta.java
- src/main/java/com/i3/delivery/domain/store/dto/StoreReviewResponsePage.java
- src/main/java/com/i3/delivery/domain/store/entity/Store.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
- src/main/java/com/i3/delivery/domain/store/service/StoreService.java
findStoreReviewAvgAndReviews 수정
1. 상태 단건 변경 메서드 추가
2. 해당 가게의 리뷰 리스트 조회 후 평균 평점값을 계산하여 page형태와 같이 리턴하게끔 변경
> Feat: Store 상태변경 기능 구현 및

- src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
1. .where(orConditions(keyword))을 통해서 and 조건으로 묶인 코드를 or 조건으로 변경.
2.  private BooleanExpression orConditions(String keyword) 키워드 검색을 통해서 하나라도 있으면 리턴
> refactor: findAll 메서드 수정

- src/main/java/com/i3/delivery/domain/product/service/ProductService.java
Product 이름 입력 시 해당 음식에 대한 설명 생성
> refactor: Product 이름 생성 로직 변경

- src/main/java/com/i3/delivery/domain/cart/dto/CartResponseDto.java
- src/main/java/com/i3/delivery/domain/cart/entity/Cart.java
- src/main/java/com/i3/delivery/domain/cart/service/CartService.java
> Fix: UUID Cart에서 제거
